"""empty message

Revision ID: b8f1f796846d
Revises: 49d8d77869c2
Create Date: 2022-12-17 16:13:18.227015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8f1f796846d'
down_revision = '49d8d77869c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('av_start', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('av_end', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_column('av_end')
        batch_op.drop_column('av_start')

    # ### end Alembic commands ###
